[package]
name = "sms-discord-relay"
version = "0.1.2"
edition = "2024"

[dependencies]
axum = { version = "0.8", default-features = false, features = ["http1", "json", "tokio"] }
hex = "0.4"
hmac = "0.12"
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls-webpki-roots"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "signal", "sync", "time"] }

tracing = { version = "0.1", default-features = false, features = ["std", "attributes"] }
tracing-log = { version = "0.2", default-features = false, features = ["std", "log-tracer"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["std", "fmt", "registry", "env-filter"] }

[dev-dependencies]
log = "0.4"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
